runtime: python39
service: default

handlers:
  # Serve the index page
  - url: /
    static_files: index.html
    upload: index.html

  # Serve static assets (images, css, js)
  - url: /(.*)
    static_files: \1
    upload: (.*)
